// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCck958orj6ULoIbyfL8BCv_K5CrXX3WZE',
    appId: '1:160026859774:ios:a55b0bb23866238583adaf',
    messagingSenderId: '160026859774',
    projectId: 'eaglevaletparking-a14cd',
    storageBucket: 'eaglevaletparking-a14cd.appspot.com',
    iosBundleId: 'com.example.eagleValetParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL4OoslDe6KfgNnpHZgj8iovK_lYq4NtA',
    appId: '1:160026859774:web:6607b7ecbca1215283adaf',
    messagingSenderId: '160026859774',
    projectId: 'eaglevaletparking-a14cd',
    authDomain: 'eaglevaletparking-a14cd.firebaseapp.com',
    storageBucket: 'eaglevaletparking-a14cd.appspot.com',
    measurementId: 'G-4S3M33KLPM',
  );
}
